[package]
name = "deck_generator"
version = "0.1.0"
edition = "2021"

[dependencies]
genanki-rs = "0.4.0"
katex = "0.4.6"
markdown = "0.3.0"
regex = "1.11.0"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
