name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/cache@v4.1.0
      with: 
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/Cargo.toml') }}
        path: |
          */target/
    - name: Run anki card generation
      run: cd deck_generator && cargo build --release && cargo run
    - uses: stefanzweifel/git-auto-commit-action@v4
        
